services:
  db:
    image: postgres:17.2
    container_name: postgres_db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123456
      - POSTGRES_DB=vaibaton_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5
  
  web:
    build: ./backend
    container_name: backend
    ports:
      - "3001:3001"
    environment:
      - DATABASE_URL=postgresql+asyncpg://postgres:123456@db:5432/vaibaton_db
      - SECRET_KEY='AFLJsKFHHKJHhfks'
      - ALGORITHM=HS256
      - REFRESH_TOKEN_EXPIRE_DAYS=7
      - SECURITY_PASSWORD_SALT='DAFSPJFHgyFA8'
      - ACCESS_TOKEN_EXPIRE_MINUTES=15
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./backend:/app


volumes:
  postgres_data: